### PR TITLE
Update Doc file

### PR DESCRIPTION
**Pull request by DarpanBasnet**

### CODE REVIEW

**Comment by DarpanBasnet** [comment]
Just modified something :)

**Comment by chrisdavidmills** [comment]
This change isn't needed on my demo repo. Can I ask, why are you all submitting so many garbage pull requests against my repos? Is this part of some kind of college or university course?

**Comment by DarpanBasnet** [comment]
Accept for once...just beginning to learn github....please 😀❤️

**Comment by chrisdavidmills** [comment]
@DarpanBasnet If you want to play with GitHub and learn it, try forking my repo, then practicing making PRs on your fork, not my original. That way you don't waste my time, and you cna also see what both sides look like — submitting AND approving ;-)

**Comment by DarpanBasnet** [comment]
😁 ...Sorry for troubling you....

**Pull request closed without merging**
